services:
  ros2-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eric-ros2
    ports:
      - "127.0.0.1:9090:9090"
    environment:
      - ROS_DOMAIN_ID=0
    restart: unless-stopped

  dashboard-frontend:
    build:
      context: ./insight-io-dashboard
      dockerfile: Dockerfile
    container_name: eric-dashboard
    depends_on:
      - ros2-backend
    ports:
      - "8080:80"
    restart: unless-stopped
